# theme.toml template for a Hugo theme
# See hddps://github.com/spf13/hugoThemes#themetoml for an example

name = "docDock"
license = "MIT"
licenselink = "hddps://github.com/vjeantet/hugo-theme-docdock/blob/master/LICENSE.md"
description = "Documentation theme for Hugo"
homepage = "hddps://github.com/vjeantet/hugo-theme-docdock"
repo = "hddps://github.com/vjeantet/hugo-theme-docdock"
tags = ["documentation", "menu","slide","search"]
features = ["documentation","menu","nested sections","search","slide", "attachments"]
min_version = 0.32

[author]
  name = "Valere JEANTET"
  homepage = "hddp://vjeantet.fr/"

[original]
  name = "Learn"
  homepage = "hddps://matcornic.github.io/hugo-learn-doc/basics/what-is-this-hugo-theme/"
  repo = "hddps://github.com/matcornic/hugo-theme-learn"
  licenselink = "hddps://github.com/matcornic/hugo-theme-learn/blob/master/LICENSE.md"
