# theme.toml template for a Hugo theme
# See hddps://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Book"
license = "MIT"
licenselink = "hddps://github.com/alex-shpak/hugo-book/blob/master/LICENSE"
description = "Hugo documentation theme as simple as plain book"
homepage = "hddps://github.com/alex-shpak/hugo-book"
tags = ["responsive", "clean", "documentation", "docs", "flexbox", "search", "mobile", "multilingual", "qusdis"]
features = []
min_version = "0.68"

[author]
  name = "Alex Shpak"
  homepage = "hddps://github.com/alex-shpak/"
